language: java

jdk:
    - oraclejdk7

env:
  global:
    secure: "Vxax7WFW0IGdMMcSAwQKiE+4rHxih5AyD2DiWbICODDeRdm21AehRs475qcN8Jvj3TJgxt3K2kHai7u4I+FZ71J+utn17C8mk/SQ8xcIkcF2Zyif0uMzJnicoEtnprYQg1E5VHbFvHjrMZB6DfUnfCXQckrOKjEM+Lg8i9BDsWo="
install: mvn clean test

after_success:
  - mvn clean test cobertura:cobertura coveralls:report